version: "3.1"

services:
  api:
    hostname: api
    container_name: api
    build: ./api/.
    ports:
      - "9999:9999"
  proxy:
    container_name: proxy
    build: ./proxy/.
    ports:
      - "8888:8888"
